[package]
name = "deepgram_rust_starters"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version="=0.5.0-rc.3", features = ["json"]}
rocket_cors = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"

dotenv = "0.15.0"
reqwest = { version = "0.11.3", features = ["json"]}
